# Generated by Django 2.0.7 on 2019-04-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descripton',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='product',
            name='summary',
            field=models.TextField(default='Default text'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
