# Generated by Django 2.0.7 on 2019-07-25 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='product',
            name='summary',
        ),
    ]
